### ISSUE TITLE
fedora config

### ISSUE THREAD

**Issue by macpijan** [mkopec/f81232-dkms#1]
Have you looked up why it was not enabled in fedora builds?
It seems to be like the only one serial adapter not enabled.

```
# CONFIG_USB_SERIAL_F81232 is not set
```

Perhaps we can request it's being enabled in the future?

**Comment by mkopec** [comment]
Good point, there's a good chance they'd accept such a change

**Comment by macpijan** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2294724

**Comment by macpijan** [comment]
Should be in 6.9.8 :smiley:  https://koji.fedoraproject.org/koji/buildinfo?buildID=2482795

**Comment by mkopec** [comment]
Cool, I confirm it's fixed in fedora now.
